blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView

appname = BlogConfig.name

urlpatterns = [
   path ('', BlogListView.as_view(),name='blog_list'),
   path('new_blog/', BlogCreateView.as_view(), name='blog_create'),
   path('edit_blog/<slug:slug>', BlogUpdateView.as_view(), name='blog_update'),
   path('view_blog/<slug:slug>', BlogDetailView.as_view(), name='blog_detail'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('catalog.urls', namespace='catalog')),
    path('', include(('blog.urls','blog'), namespace='blog')),
    path('', include(('users.urls', 'users'), namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import random

from django.db import models
from django.template.defaultfilters import truncatechars
from pytils.translit import slugify


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, unique=True, verbose_name='Slug')
    image = models.ImageField(upload_to='products/', blank=True, verbose_name='Изображение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    update_at = models.DateTimeField(auto_now=True, verbose_name='Изменен')
    is_published = models.BooleanField(default=False, verbose_name='Признак публикации')
    views_counter = models.IntegerField(default=0, verbose_name='Количество просмотров')
    content = models.TextField(verbose_name='Содержимое')

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.title}'

    @property
    def short_content(self):
        return truncatechars(self.content, 100)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = slugify(self.title)
        super(Blog,self).save(*args, **kwargs)

    @staticmethod
    def get_random_set(n:int):
        blog_set = Blog.objects.all()
        random.shuffle(blog_set)
        return blog_set[:n]

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView

from blog.models import Blog
from blog.utils import sendmail
from catalog.views import menu


class BlogListView(ListView):
    model = Blog
    extra_context = {
        'menu': menu,
        'item_selected': 'blog:blog_list',
    }


    def get_queryset(self):
        return Blog.objects.filter(is_published=True)

class BlogCreateView(CreateView):
    model = Blog
    fields = ['title', 'content', 'image', 'is_published']
    template_name = 'blog/editor.html'
    extra_context = {
        'menu': menu,
        'item_selected': 'blog:blog_list',
        'title_form': 'Добавить статью'
    }
    success_url =  reverse_lazy('blog:blog_list')

class BlogUpdateView(UpdateView):
    model = Blog
    fields = ['title', 'content', 'image', 'is_published']
    template_name = 'blog/editor.html'
    extra_context = {
        'menu': menu,
        'item_selected': 'blog:blog_list',
        'title_form': 'Изменить статью'
    }
    success_url = reverse_lazy('blog:blog_list')

    def get_success_url(self):
        return reverse('blog:blog_detail',args=(self.kwargs['slug'],))

class BlogDetailView(DetailView):
    model = Blog
    extra_context = {
        'menu': menu,
        'item_selected': 'blog:blog_list',
    }


    def get_object(self, queryset=None):
        # obj = get_object_or_404(Blog.objects,slug=self.kwargs[self.slug_url_kwarg])
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        if self.object.views_counter == 100:
            sendmail(['dtoropov@yandex.ru'], 'Домашнее задание','Ваш пост набрал 100 просмотров')
        return self.object

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}

{% block title %}
<div class="container">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Статья</h1>
            <p class="fs-5 text-body-secondary">Вы находитесь в разделе, предназначенном для размещения статей о
                товарах</p>
        </div>
    </header>
</div>
{% endblock title %}
{% load catalog_tags %}
{% block content %}
<main class="row overflow-auto">
    <div class="row">
        <div class="card-group">
            <div class="card rounded-3 shadow-sm m-1 col">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    {% if object.image %}
                    <img class="card-img-left img-thumbnail" src="{{ object.image|add_media }}">
                    {% endif %}
                    <p>
                        {{ object.content }}
                    </p>
                    <p class="text-secondary"><small>
                        Просмотров {{ object.views_counter }}
                    </small></p>

                </div>
                <div class="card-footer">
                    <a type="button" href="{% url 'blog:blog_update' object.slug %}"
                       class="m-1 w-100 btn btn-lg btn-primary">Редактировать</a>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}

{% block title %}
<header>
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">Блоги</h1>
        <p class="fs-5 text-body-secondary">Вы находитесь в разделе, предназначенном для размещения статей о товарах</p>
    </div>
</header>
{% endblock title %}
{% load catalog_tags %}
{% block content %}
<main class="row justify-content-center overflow-auto">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for object in object_list %}
        <div class="card rounded-3 shadow-sm">
            <div class="card-header w-100">
                <h4 class="my-0 fw-normal">{{ object.title }}</h4>
            </div>
            <div class="card-body">
                <p>
                    {% if object.image %}
                    <img class="card-img-left img-thumbnail" src="{{ object.image|add_media }}">
                    {% endif %}
                    {{ object.short_content }}
                </p>
            </div>
            <div class="card-footer">
                <a type="button" href="{% url 'blog:blog_detail' object.slug  %}"
                   class="m-1 w-100 btn btn-lg btn-secondary">Подробнее</a>
<!--                <button type="button" class="m-1 w-100 btn btn-lg btn-primary">Редактировать</button>-->
                <a type="button" href="{% url 'blog:blog_update' object.slug %}"
                   class="m-1 w-100 btn btn-lg btn-primary">Редактировать</a>
            </div>
        </div>
        {% endfor %}
    </div>
</main>
{% endblock content %}

blog/templates/blog/editor.html
{% extends 'base.html' %}

{% block title %}
<div class="container">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">{{title_form}}</h1>
            <p class="fs-5 text-body-secondary">Вы находитесь в разделе, предназначенном для размещения статей о товарах</p>
        </div>
    </header>
</div>
{% endblock title %}
{% load catalog_tags %}
{% block content %}
<main class="row overflow-auto">
    <div class="row">
        <div class="card-group">
            <div class="card rounded-3 shadow-sm m-1 col">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Введите информацию о товаре</h4>
                </div>
                <form method="post" action="" enctype="multipart/form-data">
                    <div class="card-body">
                        {% csrf_token %}
                        <div class="form-error">{{ form.non_field_errors }}</div>
                        {% for f in form %}
                        <p>
                            <label class="col-sm-2 col-form-label align-top" for="{{ f.id_for_label }}">{{ f.label }}</label>
                            {{ f }}
                        </p>
                        <div class="form-error">{{ f.errors }}</div>
                        {% endfor %}
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="w-100 btn btn-lg btn-primary">Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock content %}