blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView

appname = BlogConfig.name

urlpatterns = [
   path ('', BlogListView.as_view(),name='blog_list'),
   path('new_blog/', BlogCreateView.as_view(), name='blog_create'),
   path('edit_blog/<slug:slug>', BlogUpdateView.as_view(), name='blog_update'),
   path('view_blog/<slug:slug>', BlogDetailView.as_view(), name='blog_detail'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import ProductCreateView, ContactDetailView, ProductListView, ProductDetailView, \
    itsok, FeedbackCreateView, CategoryCreateView, ProductVersionCreateView, CategoryUpdateView, VersionUpdateView, \
    VersionDeleteView, CategoryDeleteView, ProductUpdateView, ProductDeleteView
from catalog.views import VersionListView, CategoryListView


app_name = 'catalog'

urlpatterns = [
    path('product/', ProductListView.as_view(), name='home'),
    path('contacts/', ContactDetailView.as_view(), name='contacts'),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('product_update/<int:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('product_delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('category_create/', CategoryCreateView.as_view(), name='create_category'),
    path('category_update/<int:pk>', CategoryUpdateView.as_view(), name='category_update'),
    path('category_delete/<int:pk>', CategoryDeleteView.as_view(), name='category_delete'),
    path('versions/', VersionListView.as_view(), name='versions'),
    path('version_update/<int:pk>', VersionUpdateView.as_view(), name='version_update'),
    path('version_delete/<int:pk>', VersionDeleteView.as_view(), name='version_delete'),
    path('version_create/', ProductVersionCreateView.as_view(), name='create_version'),
    path('editor/', ProductCreateView.as_view(), name='editor'),
    path('feedback/', FeedbackCreateView.as_view(), name='feedback'),
    path('itsok/', itsok, name='itsok')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('catalog.urls', namespace='catalog')),
    path('', include(('blog.urls','blog'), namespace='blog')),
    path('', include(('users.urls', 'users'), namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User, NULLABLE


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(blank=True, verbose_name='Описание')
    ordering = ['name']

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name']

    def __str__(self):
        return f"{self.name}"


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    price = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='Цена')
    image = models.ImageField(upload_to='products/', **NULLABLE, verbose_name='Изображение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    update_at = models.DateTimeField(auto_now=True, verbose_name='Изменен')
    category = models.ForeignKey(to=Category, on_delete=models.PROTECT,
                                 related_name='products', verbose_name='Категория')
    owner = models.ForeignKey(to=User, on_delete=models.SET_NULL, **NULLABLE,
                                 related_name='products', verbose_name='Владелец')
    is_published = models.BooleanField(default=False, verbose_name='Активно')
    # manufactured_at = models.DateField(default=datetime.datetime(2024,4,21))

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['name']
        permissions = [
            ('can_edit_description', 'может редактировать описание'),
            ('can_edit_category', 'может редактировать категорию'),
            ('can_published', 'может публиковать продукт'),
        ]

    def __str__(self):
        return f"{self.name}"

    @property
    def get_version(self):
        return self.versions.get(is_active=True)


class Contact(models.Model):
    country = models.CharField(max_length=50, verbose_name='Страна')
    inn = models.CharField(max_length=20, verbose_name='ИНН')
    address = models.CharField(max_length=255, verbose_name='Адрес')
    phone = models.CharField(max_length=30, verbose_name='Телефон')
    email = models.EmailField(verbose_name='Эл.почта')
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.email}"

    class Meta:
        ordering = ['-updated_at']
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'


class Feedback(models.Model):
    name = models.CharField(max_length=30, verbose_name='Имя')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    message = models.TextField(blank=True, verbose_name='Сообщение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    is_read = models.BooleanField(default=False, verbose_name='Прочитано')

    def __str__(self):
        return f"{self.name}, {self.created_at}"

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


class ProductVersion (models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='versions', verbose_name='продукт')
    version_name = models.CharField(max_length=50, verbose_name='название версии')
    version_number = models.CharField(max_length=50, verbose_name='номер версии')
    is_active = models.BooleanField(default=False, verbose_name='текущая версия')

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

    def __str__(self):
        return f'{self.version_name} для {self.product_name}'

    @property
    def product_name(self):
        return self.product.name

catalog/forms.py
from django import forms
from django.db.models import Q
from django.core.exceptions import ValidationError
from catalog.models import ProductVersion, Product, Category


stop_words = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар')

class BaseProductForm(forms.ModelForm):
    # name = forms.CharField(max_length=100, label='Наименование')
    # description = forms.CharField(widget=forms.Textarea(), required=False, label='Описание')
    # price = forms.DecimalField(max_digits=15, decimal_places=2, label='Цена')
    # image = forms.ImageField(required=False, label='Изображение')
    category = forms.ModelChoiceField(queryset=Category.objects.all(), label='Категория',
                                       empty_label='Категория не выбрана', required=False)

    class Meta:
        model = Product
        fields = '__all__'

    @staticmethod
    def verify_stop_words(text: str):
        for word in stop_words:
            if word in text.lower():
                raise forms.ValidationError(f'Вы используете запрещенное слово {word}')


    def clean_name(self):
        name = self.cleaned_data.get('name')
        self.verify_stop_words(name)

        return name


    def clean_description(self):
        desc = self.cleaned_data.get('description')
        self.verify_stop_words(desc)

        return desc

class ProductAdminForm(BaseProductForm):
    pass

class ProductOwnerForm(BaseProductForm):
    is_published = forms.BooleanField(disabled=True, label='Активно')

    # class Meta:
    #     fields = None
    #     exclude = ('is_published',)

class ProductModeratorForm(BaseProductForm):

    def __init__(self, *args, **kwargs):
        super(ProductModeratorForm, self).__init__(*args, **kwargs)
        self.fields['name'].disabled = True
        self.fields['price'].disabled = True
        self.fields['image'].disabled = True
        self.fields['owner'].disabled = True

class ProductVersionForm(forms.ModelForm):

    class Meta:
        model = ProductVersion
        fields = '__all__'

    def clean_is_active(self):
        is_active = self.cleaned_data['is_active']
        if is_active:
            obj = self.cleaned_data['product']
            flag = obj.versions.filter(Q(is_active=True) & ~Q(pk=self.instance.id)).exists()
            if flag:
                raise ValidationError('Уже есть активная версия для этого продукта')

        return is_active


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductOwnerForm, CategoryForm, ProductVersionForm, ProductAdminForm, ProductModeratorForm
from catalog.models import Product, Contact, Feedback, Category, ProductVersion
from utils import get_categories_from_cache

menu = [{'title': "Главная", 'url_name': 'catalog:home', 'svg_name': 'home', 'visibility': True},
        {'title': "Категории", 'url_name': 'catalog:categories', 'svg_name': 'speedometer2', 'visibility': True},
        {'title': "Версии", 'url_name': 'catalog:versions', 'svg_name': 'table', 'visibility': True},
        {'title': "Контакты", 'url_name': 'catalog:contacts', 'svg_name': 'people-circle', 'visibility': True},
        # {'title': "Редактор", 'url_name': 'catalog:editor', 'svg_name': 'grid', 'visibility': True},
        {'title': "Статьи", 'url_name': 'blog:blog_list', 'svg_name': 'collection', 'visibility': True},
        ]


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'catalog/product_list.html'
    paginate_by = 3
    extra_context = {
        'menu': menu,
        'item_selected': 'catalog:home',
    }
    ordering = ['-created_at']

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser or user.is_moderator:
            return Product.objects.all()

        return Product.objects.filter(Q(is_published=True)|Q(owner=self.request.user))


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context


class ContactDetailView(DetailView):
    template_name = 'catalog/contacts.html'
    extra_context = {
        'menu': menu,
        'item_selected': 'catalog:contacts',
    }
    context_object_name = 'data'

    def get_object(self, **kwargs):
        queryset = Contact.objects.order_by('-updated_at')
        obj = queryset.first()
        return obj


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'catalog/product.html'
    extra_context = {
        'menu': menu,
        'item_selected': '',
    }



class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductOwnerForm
    template_name = 'catalog/editor.html'
    extra_context = {
        'menu': menu,
        'item_selected': 'catalog:editor',
        'title_form': 'Добавить товар'
    }
    success_url = reverse_lazy('catalog:home')

    def form_valid(self, form):
        user = form.save()
        user.owner = self.request.user
        user.save()

        return super().form_valid(form)

class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    template_name = 'catalog/editor.html'
    form_class = ProductAdminForm
    extra_context = {
        'menu': menu,
        'item_selected': 'catalog:home',
        'title_form': 'Редактировать товар',
        'footer_url': 'catalog:product_delete'
    }
    success_url = reverse_lazy('catalog:home')

    def get_form_class(self):

        user = self.request.user
        if user.is_superuser:
            return ProductAdminForm
        elif user == self.object.owner:
            return ProductOwnerForm
        elif user.is_moderator:
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = 'catalog/delete.html'
    success_url = reverse_lazy('catalog:home')
    extra_context = {
        'menu': menu,
        'item_selected': 'catalog:home',
        'title': 'Удаление товара',
        'title_card': 'товар',
        'title_href': {'url': 'catalog:product_update'},
    }

class FeedbackCreateView(CreateView):
    model = Feedback
    fields = ['name', 'phone', 'message']
    template_name = 'catalog/editor.html'
    extra_context = {
        'menu': menu,
        # 'item_selected': 'catalog:editor',
        'title_form': 'Обратная связь'
    }
    success_url = reverse_lazy('catalog:itsok')


def itsok(request):
    context = {
        'menu': menu,
    }
    return render(request, 'catalog/itsok.html', context=context)


class VersionListView(LoginRequiredMixin, ListView):
    model = ProductVersion
    paginate_by = 4
    extra_context = {
        'menu': menu,
        'item_selected': 'catalog:versions',
    }

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser or user.is_moderator:
            return ProductVersion.objects.all()

        return ProductVersion.objects.filter(product__owner=self.request.user)


class VersionUpdateView(LoginRequiredMixin, UpdateView):
    model = ProductVersion
    form_class = ProductVersionForm
    template_name = 'catalog/editor.html'
    extra_context = {
        'menu': menu,
        'item_selected': 'catalog:versions',
        'title_form': 'Редактировать версию',
        'footer_url': 'catalog:version_delete'
    }
    success_url = reverse_lazy('catalog:versions')

    # def form_valid(self, form):
    #     if form.is_valid():
    #         obj = form.save(commit=False)
    #         if obj.is_active:
    #             if obj.product.versions.filter(Q(is_active=True) & ~Q(pk=obj.pk) ):
    #                 raise ValidationError('Уже есть активная версия для этого продукта')
    #
    #     return super().form_valid(form)


class VersionCreateView(LoginRequiredMixin, CreateView):
    model = ProductVersion
    form_class = ProductVersionForm
    template_name = 'catalog/editor.html'
    extra_context = {
        'menu': menu,
        'item_selected': 'catalog:versions',
        'title_form': 'Добавить версию'
    }
    success_url = reverse_lazy('catalog:home')


class VersionDeleteView(LoginRequiredMixin, DeleteView):
    model = ProductVersion
    template_name = 'catalog/delete.html'
    success_url = reverse_lazy('catalog:versions')
    extra_context = {
        'menu': menu,
        'item_selected': 'catalog:versions',
        'title': 'Удаление версии',
        'title_card': 'версию',
        'title_href': {'url': 'catalog:version_update'},
    }


class ProductVersionCreateView(LoginRequiredMixin, CreateView):
    model = ProductVersion
    form_class = ProductVersionForm
    template_name = 'catalog/editor.html'
    extra_context = {
        'menu': menu,
        'title_form': 'Добавить версию'
    }
    success_url = reverse_lazy('catalog:home')


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    paginate_by = 4
    extra_context = {
        'menu': menu,
        'item_selected': 'catalog:categories',
    }

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser or user.is_moderator:
            return get_categories_from_cache()

        raise PermissionDenied

class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'catalog/editor.html'
    extra_context = {
        'menu': menu,
        'item_selected': 'catalog:categories',
        'title_form': 'Редактировать категорию',
        'footer_url': 'catalog:category_delete'

    }
    success_url = reverse_lazy('catalog:categories')


class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = Category
    template_name = 'catalog/delete.html'
    success_url = reverse_lazy('catalog:versions')
    extra_context = {
        'menu': menu,
        'item_selected': 'catalog:versions',
        'title': 'Удаление категории',
        'title_card': 'категорию',
        'title_href': {'url': 'catalog:category_update'},
    }


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'catalog/editor.html'
    extra_context = {
        'menu': menu,
        'title_form': 'Добавить категорию'
    }
    success_url = reverse_lazy('catalog:home')

catalog/templates/catalog/category_list.html
{% extends 'base.html' %}

{% block title %}
<div class="container">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">О товаре</h1>
            <p class="fs-5 text-body-secondary">Вы находитесь на сайте, предназначенном для продажи товаров</p>
        </div>
    </header>
</div>
{% endblock title %}
{% load catalog_tags %}
{% block content %}
<main class="row overflow-auto">
    <div class="row">
        <div class="card-group">
            {% for object in object_list %}
            <div class="card rounded-3 shadow-sm m-1 col">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <p>
                        {{ object.description }}
                    </p>
                </div>
                <div class="card-footer">
                    <a type="button" href="{% url 'catalog:category_update' object.pk %}"
                       class="m-1 w-100 btn btn-lg btn-primary">Редактировать</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock content %}

catalog/templates/catalog/contacts.html
{% extends 'base.html' %}

{% block title %}
<header>
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">Контакты</h1>
        <p class="fs-5 text-body-secondary">Вы находитесь на сайте, предназначенном для продажи товаров</p>
    </div>
</header>
{% endblock title%}

{% block content %}
<div class="row text-center">
    <div class="col-lg-9 col-md-6 col-sm-12 mx-auto">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>{{data.country}}</td>
                    </tr>
                    <tr>
                        <td class="w-25">ИНН</td>
                        <td>{{data.inn}}</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>{{data.address}}</td>
                    </tr>
                    <tr>
                        <td class="w-25">Телефон</td>
                        <td>{{data.phone}}</td>
                    </tr>
                    <tr>
                        <td class="w-25">Эл.почта</td>
                        <td>{{data.email}}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

catalog/templates/catalog/delete.html
{% extends 'base.html' %}

{% block content %}

<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">{{ title }}</h1>

            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between">
                    <span>
                    <i class="fas fa-table me-1"></i>
                    Вы действительно хотите удалить {{ title_card }}?
                    </span>
                </div>
                <div class="card-body">
                    <p>
                    <h4>
                        {{object}}
                    </h4>
                    </p>
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>
                            <button type="submit" class="gy-2 w-100 btn btn-lg btn-outline-danger">Удалить</button>
                        </p>
                        <p>
                            <a href="{% url title_href.url object.pk %}"
                               class="gy-2 w-100 btn btn-lg btn-outline-primary">Отменить</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </main>


</div>
{% endblock content %}

catalog/templates/catalog/editor.html
{% extends 'base.html' %}

{% block title %}
<div class="container">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">{{title_form}}</h1>
            <p class="fs-5 text-body-secondary">Вы находитесь на сайте, предназначенном для продажи товаров</p>
        </div>
    </header>
</div>
{% endblock title %}
{% load catalog_tags %}
{% block content %}
<main class="row overflow-auto">
    <div class="row">
        <div class="card-group">
            <div class="card rounded-3 shadow-sm m-1 col">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Введите информацию о товаре</h4>
                </div>
                <form method="post" action="" enctype="multipart/form-data">
                    <div class="card-body">
                        {% csrf_token %}
                        <div class="form-error">{{ form.non_field_errors }}</div>
                        {% for f in form %}
                        <p>
                            <label class="col-sm-2 col-form-label align-top" for="{{ f.id_for_label }}">
                                {{ f.label }}</label>
                            {{ f }}
                        </p>
                        <div class="form-error">{{ f.errors }}</div>
                        {% endfor %}
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="my-2 w-100 btn btn-lg btn-primary">Сохранить</button>
                        {% if footer_url %}
                        <a type="button" href="{% url footer_url object.pk %}"
                           class="my-2 w-100 btn btn-lg btn-secondary">Удалить</a>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

catalog/templates/catalog/feedback.html
{% extends 'base.html' %}

{% block title %}
<header>
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis"></h1>
        <p class="fs-5 text-body-secondary">Вы находитесь на сайте, предназначенном для продажи товаров</p>
    </div>
</header>
{% endblock title%}

{% block content %}
<div class="row text-start">
    <div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone"
                               placeholder="Контактный телефон" required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea type="text" name="message" class="form-control" id="message"
                                  placeholder="Текст сообщения" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-primary">Отправить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

catalog/templates/catalog/index.html
{% extends 'base.html' %}

{% block title %}
<header>
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">Главная</h1>
        <p class="fs-5 text-body-secondary">Вы находитесь на сайте, предназначенном для продажи товаров</p>
    </div>
</header>
{% endblock title %}
{% load catalog_tags %}
{% block content %}
<main class="row justify-content-center overflow-auto">
    <div class="row row-cols-1 row-cols-md-3">
        {% for object in object_list %}
        <div class="card rounded-3 shadow-sm">
            <div class="card-header w-100">
                <h4 class="my-0 fw-normal">{{ object.name }}</h4>
            </div>
            <div class="card-body">
                <h2 class="card-title pricing-card-title">{{ object.price }}</h2>
                <p>
                    {% if object.image %}
                    <img class="card-img-left img-thumbnail" src="{{ object.image|add_media }}">
                    {% endif %}
                    {{ object.description | slice:150 }}
                </p>
                <div class="text-secondary">
                    {% if object.get_version %}
                    Version: {{ object.get_version.version_number }}
                    {% endif %}
                </div>
            </div>
            <div class="card-footer">
                <a type="button" href="{% url 'catalog:product' object.pk %}"
                   class="m-1 w-100 btn btn-lg btn-secondary">Подробнее</a>
                <button type="button" class="m-1 w-100 btn btn-lg btn-primary">Купить</button>
            </div>
        </div>
        {% endfor %}
    </div>
</main>
{% endblock content %}

catalog/templates/catalog/itsok.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div class="container row h-100 justify-content-center">
        <div class="card rounded-3 shadow-sm m-1 text-center w-25 center-card">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Success</h4>
            </div>

            <div class="card-body">
                <p> Thank's for feedback </p>
            </div>
            <div class="card-footer">
                <a href="/contacts/" class="w-100 btn btn-primary btn-lg active" role="button"
                   aria-pressed="true">OK</a>
            </div>
        </div>
    </div>
    </div>
</main>

{% endblock content %}

catalog/templates/catalog/product.html
{% extends 'base.html' %}

{% block title %}
<div class="container">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">О товаре</h1>
            <p class="fs-5 text-body-secondary">Вы находитесь на сайте, предназначенном для продажи товаров</p>
        </div>
    </header>
</div>
{% endblock title %}
{% load catalog_tags %}
{% block content %}
<main class="row overflow-auto">
    <div class="row">
        <div class="card-group">
            <div class="card rounded-3 shadow-sm m-1 col">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <h2 class="card-title pricing-card-title">{{ object.price }}</h2>
                    {% if object.image %}
                    <img class="card-img-left img-thumbnail" src="{{ object.image|add_media }}">
                    {% endif %}<p>
                        {{ object.description }}
                    </p>
                </div>
                <div class="card-footer">
                    <button type="button" class="m-2 w-100 btn btn-lg btn-primary">Купить</button>
                    {% if user.is_superuser or user.is_moderator or object.owner == user %}
                    <a type="button" href="{% url 'catalog:product_update' object.pk %}"
                       class="m-2 w-100 btn btn-lg btn-secondary">Редактировать</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

catalog/templates/catalog/product_list.html
{% extends 'base.html' %}

{% block title %}
<header>
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">Главная</h1>
        <p class="fs-5 text-body-secondary">Вы находитесь на сайте, предназначенном для продажи товаров</p>
    </div>
</header>
{% endblock title %}
{% load catalog_tags %}
{% block content %}
<main class="row justify-content-center overflow-auto">
    <div class="row row-cols-1 row-cols-md-3">
        {% for object in object_list %}
        <div class="card rounded-3 shadow-sm">
            <div class="card-header w-100">
                <h4 class="my-0 fw-normal">{{ object.name }}</h4>
            </div>
            <div class="card-body">
                <h2 class="card-title pricing-card-title">{{ object.price }}</h2>
                <p>
                    {% if object.image %}
                    <img class="card-img-left img-thumbnail" src="{{ object.image|add_media }}">
                    {% endif %}
                    {{ object.description | slice:150 }}
                </p>
                <div class="text-secondary">
                    {% if object.get_version %}
                    Version: {{ object.get_version.version_number }}
                    {% endif %}
                </div>
            </div>
            <div class="card-footer">
                <a type="button" href="{% url 'catalog:product' object.pk %}"
                   class="m-1 w-100 btn btn-lg btn-secondary">Подробнее</a>
                <button type="button" class="m-1 w-100 btn btn-lg btn-primary">Купить</button>
            </div>
        </div>
        {% endfor %}
    </div>
</main>
{% endblock content %}